server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deveventos?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    platform: org.hibernate.dialect.MySQL5Dialect
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update